## Numpy

In [1]:
import numpy as np

* `np` slices and item definitions work just as you would expect them to work, given how Python strings behave, except that `np` returns *views*, not *copies*. To get deep copies we need to use `.copy()`.
* You can do boolean tests on `array` objects, stuff like `data < .7`. This will run itemwise on all entries.
* The `True`/`False` array that results from such an operation can be used to mask another array.

In [3]:
data = np.random.randn(7,4)
data

array([[-1.10392516, -0.73419721, -0.03319868,  1.43218872],
       [-0.66224372, -0.33220617,  0.2196389 ,  0.15853764],
       [-0.2029212 ,  1.66008   , -0.05529851, -0.34418627],
       [-0.09484954,  0.2840521 ,  0.24068879, -1.09816302],
       [-0.97853027, -0.1406235 ,  2.26031439, -0.27595093],
       [-0.55694088,  0.50494445,  0.10231247, -1.46111122],
       [ 1.45342739,  0.36767458, -1.47607057, -0.92812649]])

In [4]:
data[:1]

array([[-1.10392516, -0.73419721, -0.03319868,  1.43218872]])

In [5]:
data < .7

array([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]], dtype=bool)

In [6]:
data[data < .7]

array([-1.10392516, -0.73419721, -0.03319868, -0.66224372, -0.33220617,
        0.2196389 ,  0.15853764, -0.2029212 , -0.05529851, -0.34418627,
       -0.09484954,  0.2840521 ,  0.24068879, -1.09816302, -0.97853027,
       -0.1406235 , -0.27595093, -0.55694088,  0.50494445,  0.10231247,
       -1.46111122,  0.36767458, -1.47607057, -0.92812649])

In [7]:
data[data < .7].shape

(24,)

* You can matrix multiply boolean masks across arrays. This will remove false-multiplied columns.

In [8]:
names = np.array(['Al', 'Bo', 'Bo', 'Bo', 'Al', 'Al', 'Bo'])
names

array(['Al', 'Bo', 'Bo', 'Bo', 'Al', 'Al', 'Bo'], 
      dtype='<U2')

In [9]:
names != 'Al'

array([False,  True,  True,  True, False, False,  True], dtype=bool)

In [11]:
data

array([[-1.10392516, -0.73419721, -0.03319868,  1.43218872],
       [-0.66224372, -0.33220617,  0.2196389 ,  0.15853764],
       [-0.2029212 ,  1.66008   , -0.05529851, -0.34418627],
       [-0.09484954,  0.2840521 ,  0.24068879, -1.09816302],
       [-0.97853027, -0.1406235 ,  2.26031439, -0.27595093],
       [-0.55694088,  0.50494445,  0.10231247, -1.46111122],
       [ 1.45342739,  0.36767458, -1.47607057, -0.92812649]])

In [12]:
data[names != 'Al']

array([[-0.66224372, -0.33220617,  0.2196389 ,  0.15853764],
       [-0.2029212 ,  1.66008   , -0.05529851, -0.34418627],
       [-0.09484954,  0.2840521 ,  0.24068879, -1.09816302],
       [ 1.45342739,  0.36767458, -1.47607057, -0.92812649]])

* Array bitwise logical operations are via `|` and `&`.

In [13]:
np.array([False, False]) | np.array([True, True])

array([ True,  True], dtype=bool)

In [14]:
np.array([False, True]) & np.array([True, False])

array([False, False], dtype=bool)

* You can assign data based on a mask.

In [16]:
data[data < .7] = 0
data

array([[ 0.        ,  0.        ,  0.        ,  1.43218872],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.66008   ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.26031439,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.45342739,  0.        ,  0.        ,  0.        ]])